### ISSUE TITLE
Prepare load testing

### ISSUE THREAD

**Issue by jnehring** [freme-project/load-testing#3]
- Rename "total time per request" to "total time to process dataset".
- Make average size of request constant

**Comment by josauder** [comment]
Test should now represent what you wished it looks like. 
We now switched to a pure python loadtest
I left the jmeter test in the repo but made sure it is clear that everyone sees it is deprecated.
I suggest you change the description of this repo from 
"Load testing of FREME using Apache JMeter" to
"Load testing of FREME" (I don't have permission to do so)

**Comment by jnehring** [comment]
this issue is no longer valid
