### ISSUE TITLE
Assertion

### ISSUE THREAD

**Issue by x-fran** [freme-project/load-testing#4]
I would use "AssertionError" instead "Exception" for try catch block in loadtest.py
Using argparse probably it is a good idea also.

**Comment by jnehring** [comment]
@xFran did you find a bug? Is this a problem or just an aesthetic problem?

**Comment by x-fran** [comment]
@jnehring In the python community using Exception instead  "AssertionError" for assertions and Exception instead "ImportError" is considered not "pythonic".
"Argparse"  module makes easy to write user-friendly command-line interfaces.
If this tool is not heavily used for other developers than is just fine as it is.
